### PR TITLE
Youtube updates

### PR DESCRIPTION
**Pull request by muydanny**
Added v0.3 YouTube videos to the events.yml and changed the hover on the sponsors. The sponsors initially had opacity then brightened on the hover and I switched it so its they are brighter on the page. I also made them slightly larger when hovered over. Also closed CFP.
Screen Shot 2021-04-14 at 10 24 56 PM
Screen Shot 2021-04-14 at 10 23 49 PM
Screen Shot 2021-04-14 at 10 26 17 PM

### CODE REVIEW

**Comment by ChaelCodes** [comment]
Please add new guests, and I'll approve.

**Comment by muydanny** [comment]
Added new guests. Couldn't figure out how to get photos to float the left of the abstract or a solution to the photos being so large. Let me know what you think 👍🏽
Screen Shot 2021-04-16 at 12 00 01 AM
Screen Shot 2021-04-16 at 12 00 18 AM
Screen Shot 2021-04-16 at 12 00 29 AM

**Comment by muydanny** [comment]
Also Im kinda guessing this is Dan. From what was in Paper Call this is what who I found on Twitter lol

**Comment by muydanny** [comment]
Ok I realized Paper Call gives us all their info in a JSON file so everything is 💯
I looked over the site once more and I didn't like the large photos. After looking at how other conferences like Rails Conf do it I redesigned it.

- Added `Hosted by` with links
- Removed Photos
- Added Author Bios to highlight Authors more than previously
Screen Shot 2021-04-16 at 12 37 43 PM
Screen Shot 2021-04-16 at 12 37 50 PM

**Review by ChaelCodes — APPROVED** [review]
I love what you've done with the site!

**Pull request merged**
