### PR TITLE
Kh.add cfp link to the homepage

### PR DESCRIPTION
**Pull request by wyhaines**
This adds a link to the CFP site for the front page.

### CODE REVIEW

**Comment by wyhaines** [comment]
image

**Comment by muydanny** [comment]
This is great, thank you Kirk!

**Comment by joelhawksley** [comment]
👋🏻 I've submitted a proposal via PaperCall, but noticed that `Submit a Talk` in the top navigation links to this repo. Would you still prefer for PRs to be opened against this repo for proposals?

**Comment by muydanny** [comment]
Hey @joelhawksley! Thank you so much for submitting a talk! We actually need to change the `Submit a Talk` button to link to Papercall, so thank you for bringing this up!

**Pull request merged**
